title: "Data-cloud2.0"
description: "The best way to learn programming is to write programs."
theme: just-the-docs

# Navigation settings
just_the_docs:
  search_enabled: true
  navigation:
    - title: "Home"
      url: "/"
    - title: "Course Overview"
      url: "/course_overview"
    - title: "Learning Objectives"
      url: "/learning_objectives"
    - title: "Roadmap"
      url: "/roadmap"
